WITH BR AS (SELECT REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES,
ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS BEST_RANK
FROM REST_INFO)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM BR
WHERE BEST_RANK = 1
ORDER BY 1 DESC;