-- 중고 거래 게시물을 3건 이상 등록한 사용자
-- 사용자 ID, 닉네임, 전체주소, 전화번호를 조회

SELECT USER_ID, NICKNAME, 
CONCAT(CITY,' ',STREET_ADDRESS1, ' ',STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(TLNO,3),'-',MID(TLNO,4,4),'-',RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_USER U
JOIN (SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(*) >=3) W
ON U.USER_ID = W.WRITER_ID
ORDER BY USER_ID DESC;