-- 코드를 입력하세요
-- 중성화 전(Intact) 후 (Spayed)

# 보호소에 들어올 때는 중성화 X
# 보호소 나갈떄는 중성화

# 로직: ANIMAL_INS랑 ANIMAL_OUTS랑 조인하고 중성화X & 중성화O랑 고르기

SELECT I.ANIMAL_ID AS ANIMAL_ID, I.ANIMAL_TYPE AS ANIMAL_TYPE, I.NAME AS NAME
FROM ANIMAL_INS AS I
JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE LEFT(I.SEX_UPON_INTAKE,6) = 'Intact' AND (LEFT(O.SEX_UPON_OUTCOME, 6) = 'Spayed' OR LEFT(O.SEX_UPON_OUTCOME, 8) = 'Neutered')
ORDER BY I.ANIMAL_ID ASC

/*
SELECT *
FROM ANIMAL_INS
WHERE LEFT(I.SEX_UPON_INTAKE,6) = 'Intact'


SELECT *
FROM ANIMAL_OUTS
WHERE LEFT(O.SEX_UPON_OUTCOME, 6) = 'Spayed' | LEFT(O.SEX_UPON_OUTCOME, 6) = 'Neutered'

SELECT I.ANIMAL_ID, I.NAME, I.SEX_UPON_INTAKE, O.SEX_UPON_OUTCOME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE LEFT(I.SEX_UPON_INTAKE, 6) = 'Intact'
  AND (LEFT(O.SEX_UPON_OUTCOME, 6) = 'Spayed' OR LEFT(O.SEX_UPON_OUTCOME, 6) = 'Neuter');
*/