# SELECT I.FISH_COUNT AS FISH_COUNT,N.FISH_NAME AS FISH_NAME
# FROM FISH_NAME_INFO N
# JOIN (
#     SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE) I
# ON N.FISH_TYPE = I.FISH_TYPE
# ORDER BY I.FISH_COUNT DESC;

SELECT 
    COUNT(*) AS FISH_COUNT,
    N.FISH_NAME
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
  ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY FISH_COUNT DESC;
