-- 코드를 입력하세요

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * AMOUNT_SUM AS TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT_SUM
FROM FOOD_ORDER
WHERE LEFT(PRODUCE_DATE,7) = '2022-05'
GROUP BY PRODUCT_ID) AS FO
JOIN FOOD_PRODUCT AS FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;