-- 코드를 입력하세요
WITH L_3 AS (SELECT H.FLAVOR, SUM(H.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS SUM_ORDER
FROM FIRST_HALF AS H
JOIN JULY AS J
ON H.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM_ORDER DESC
LIMIT 3)
SELECT FLAVOR
FROM L_3;