-- ITEM_A(ROOT / B의 PARENT 아이템) -> ITEM_B(C의 PARENT 아이템) -> ITEM_C

SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM (SELECT * FROM ITEM_INFO WHERE RARITY = 'RARE') AS I
LEFT JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO AS II ON II.ITEM_ID = T.ITEM_ID
ORDER BY II.ITEM_ID DESC;