SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(C.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C

JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
) FILTER_C
ON C.CAR_ID = FILTER_C.CAR_ID

WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
HAVING COUNT(C.HISTORY_ID) > 0
ORDER BY 1 ASC, 2 DESC;