-- 코드를 작성해주세요
SELECT ED.YEAR, (ED.MAX_SIZE - E.SIZE_OF_COLONY) YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) AS ED
ON YEAR(E.DIFFERENTIATION_DATE) = ED.YEAR
ORDER BY 1, 2;