-- 2022년 1월의 카테고리 별 도서 판매량을 합산
-- 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
-- 카테고리명을 기준으로 오름차순 
/*SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS S
WHERE LEFT(S.SALES_DATE,7) = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY*/

-- 책별 판매량 구하기
WITH BS AS (SELECT S.BOOK_ID, SUM(S.SALES) AS ID_SUM
FROM BOOK_SALES AS S
WHERE LEFT(S.SALES_DATE,7) = '2022-01'
GROUP BY S.BOOK_ID)

-- JOIN을 통해 카테고리별 판매량 구하기
SELECT B.CATEGORY, SUM(BS.ID_SUM)
FROM BS
LEFT JOIN BOOK AS B ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
