-- 식품분류별/ 가격이 제일 비싼/ 식품의 분류, 가격, 이름 조회
-- 식품분류가 '과자', '국', '김치', '식용류' 만
WITH FT_FOOD AS(
SELECT RANK( ) OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) PRICE_RANK,
CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유'))
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FT_FOOD
WHERE PRICE_RANK = 1
ORDER BY MAX_PRICE DESC;